### ISSUE TITLE
Did some corrections so it compiles in MSVC Windows

### ISSUE THREAD

**Issue by juandent** [Erroneous1/sqlpp11-connector-odbc#1]
[see link](https://github.com/juandent/sqlpp11-connector-odbc/tree/jd-develop)

Please let me know if I am using git correctly or if is a better way to let you know of changes in odbc connector.

Regards,
Juan

**Comment by Erroneous1** [comment]
What version of msvc are you working on? I have access to VS 2013 so I could help confirm stuff if needed. Did you get the tests to work with the all_of issue?

For -DNOMINMAX, you could do
`if(WIN32)`
`add_definitions(-DNOMINMAX )`
`endif()`
so that it doesn't have unforseen side effects on other compilers.

For ODBC_INCLUDE_DIRECTORIES and DATE_INCLUDE_DIR you should set these in your cmake project configuration instead of putting it in the CMakeLists.txt. I'm still a novice at CMake but it should use those values if you set them manually.

Once you've done this make a pull request on my repo with the commits and I'll put in the changes.

**Comment by Erroneous1** [comment]
Are you still getting errors?

I just released 0.03 but didn't implement any of your changes in your repo. I'm closing this bug until I get a PR.

If you have to have the `#include`s in order to compile the dll/lib then please wrap them in `#ifdef _MSC_VER` or `#ifdef _WIN32`.
If you can compile the dll/lib without those `#include`s then just include them before you include the sqlpp11-connector-odbc headers.
Try _MSC_VER first if you can and try compiling using clang++ or g++ in windows to see if you need those includes just for MSVC.
